"""跨服务统一错误码（集成文档 §60 / 收尾文档 §49）。"""
from __future__ import annotations

CONTRACT_VERSION_UNSUPPORTED = "CONTRACT_VERSION_UNSUPPORTED"
DATA_NOT_READY = "DATA_NOT_READY"
SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
SNAPSHOT_CORRUPTED = "SNAPSHOT_CORRUPTED"
DATA_QUALITY_REJECTED = "DATA_QUALITY_REJECTED"
LOOKAHEAD_VIOLATION = "LOOKAHEAD_VIOLATION"
PIT_DATA_MISSING = "PIT_DATA_MISSING"
PIT_METADATA_MISSING = "PIT_METADATA_MISSING"
BACKTEST_FAILED = "BACKTEST_FAILED"
FACTOR_UNAVAILABLE = "FACTOR_UNAVAILABLE"
CONTENT_UNAVAILABLE = "CONTENT_UNAVAILABLE"
FACTOR_NOT_PROMOTED = "FACTOR_NOT_PROMOTED"
FACTOR_OOS_NOT_AUTHORIZED = "FACTOR_OOS_NOT_AUTHORIZED"
FACTOR_OOS_INVALIDATED = "FACTOR_OOS_INVALIDATED"
RISK_VETO = "RISK_VETO"
EXECUTION_REJECTED = "EXECUTION_REJECTED"
QMT_UNAVAILABLE = "QMT_UNAVAILABLE"

ALL_ERROR_CODES = (
    CONTRACT_VERSION_UNSUPPORTED,
    DATA_NOT_READY,
    SNAPSHOT_NOT_FOUND,
    SNAPSHOT_CORRUPTED,
    DATA_QUALITY_REJECTED,
    LOOKAHEAD_VIOLATION,
    PIT_DATA_MISSING,
    PIT_METADATA_MISSING,
    BACKTEST_FAILED,
    FACTOR_UNAVAILABLE,
    CONTENT_UNAVAILABLE,
    FACTOR_NOT_PROMOTED,
    FACTOR_OOS_NOT_AUTHORIZED,
    FACTOR_OOS_INVALIDATED,
    RISK_VETO,
    EXECUTION_REJECTED,
    QMT_UNAVAILABLE,
)
