"""跨服务统一错误码（设计文档 §60）。"""
from __future__ import annotations

CONTRACT_VERSION_UNSUPPORTED = "CONTRACT_VERSION_UNSUPPORTED"
DATA_NOT_READY = "DATA_NOT_READY"
SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
LOOKAHEAD_VIOLATION = "LOOKAHEAD_VIOLATION"
PIT_DATA_MISSING = "PIT_DATA_MISSING"
BACKTEST_FAILED = "BACKTEST_FAILED"
FACTOR_NOT_PROMOTED = "FACTOR_NOT_PROMOTED"
RISK_VETO = "RISK_VETO"
EXECUTION_REJECTED = "EXECUTION_REJECTED"
QMT_UNAVAILABLE = "QMT_UNAVAILABLE"

ALL_ERROR_CODES = (
    CONTRACT_VERSION_UNSUPPORTED,
    DATA_NOT_READY,
    SNAPSHOT_NOT_FOUND,
    LOOKAHEAD_VIOLATION,
    PIT_DATA_MISSING,
    BACKTEST_FAILED,
    FACTOR_NOT_PROMOTED,
    RISK_VETO,
    EXECUTION_REJECTED,
    QMT_UNAVAILABLE,
)
